In [12]:
import torch

In [13]:
torch.__version__

'2.0.1+cpu'

In [14]:
torch.cuda.is_available()

False

In [15]:
# creating pytorch tensors 
tensor_0_d = torch.tensor(1)
tensor_1_d = torch.tensor([1,2,4])
tensor_2_d = torch.tensor([[1,2,4],[2,35,1]])
tensor_3_d = torch.tensor([[[1,4],[3,4]],[[5,6],[7,8]]])

In [16]:
# tensor data type 
tensor_0_d.dtype

torch.int64

In [18]:
# float tensor data type 
floatvec = torch.tensor([1.0,2.0,3.0])
print(floatvec.dtype)

torch.float32


In [23]:
# convert type from tensor.int to tensor.float 
floatvec = tensor_2_d.to(torch.float32)
floatvec,floatvec.dtype

(tensor([[ 1.,  2.,  4.],
         [ 2., 35.,  1.]]),
 torch.float32)

In [29]:
# origin tensor_2_d
tensor_2_d

tensor([[ 1,  2,  4],
        [ 2, 35,  1]])

In [36]:
# reshaping tensor_3_d to
tensor_2_d_1 = tensor_2_d.reshape((3,2))
tensor_2_d_1.shape, tensor_2_d_1

(torch.Size([3, 2]),
 tensor([[ 1,  2],
         [ 4,  2],
         [35,  1]]))

In [39]:
# second way to reshaping with view
tensor_2_d.view(3,2)

tensor([[ 1,  2],
        [ 4,  2],
        [35,  1]])

In [41]:
# transpose a tensor 
tensor_2_d.T

tensor([[ 1,  2],
        [ 2, 35],
        [ 4,  1]])

In [42]:
# multiply two matrix in pytorch 
tensor_2_d.matmul(tensor_2_d.T)

tensor([[  21,   76],
        [  76, 1230]])

In [45]:
# the second way to multiply two matrix 
tensor_2_d @ tensor_2_d.T

tensor([[  21,   76],
        [  76, 1230]])