### A logistic regression forward pass 

In [14]:
import torch.nn.functional as F
import torch
from torch.autograd import grad

In [17]:
y= torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0] , requires_grad=True)

In [18]:
# compute in an output layer
z = x1*w1+b
a = torch.sigmoid(z)

In [19]:
a, z

(tensor([0.9183], grad_fn=<SigmoidBackward0>),
 tensor([2.4200], grad_fn=<AddBackward0>))

In [20]:
loss = F.binary_cross_entropy(a,y)

In [21]:
loss

tensor(0.0852, grad_fn=<BinaryCrossEntropyBackward0>)

### Updating w1 and b

In [22]:
grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

In [23]:
print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)
